name: Run Tests on Dev Changes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Start local server
      - name: Start local server
        run: |
          npm start &
          echo $! > server.pid
          sleep 20

      # Step 6: Run tests
      - name: Run tests
        run: |
          sleep 20
          if nc -z localhost 4000; then
            echo "Server Running."
          else
            echo "Tests skipped because the server is not running."
            exit 1
          fi

      # Step 7: Stop local server
      - name: Stop local server
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || echo "Server already stopped."
          fi
          rm -f server.pid
